<!-- Core JS files -->
<script src="<?php echo base_url('global_assets/js/main/jquery.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/main/bootstrap.bundle.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/loaders/blockui.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/ui/ripple.min.js') ?>"></script>
<!-- /core JS files -->

<!-- Theme JS files -->
<script src="<?php echo base_url('global_assets/js/plugins/visualization/d3/d3.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/visualization/d3/d3_tooltip.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/forms/styling/switchery.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/ui/moment/moment.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/pickers/daterangepicker.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/forms/styling/uniform.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/extensions/jquery_ui/interactions.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/forms/selects/select2.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/forms/inputs/touchspin.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/forms/styling/switch.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/pickers/anytime.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/pickers/pickadate/picker.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/pickers/pickadate/picker.date.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/pickers/pickadate/picker.time.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/tables/datatables/datatables.min.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/plugins/forms/selects/select2.min.js') ?>"></script>

<script src="<?php echo base_url('assets/js/app.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/dashboard.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/form_inputs.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/form_select2.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/form_input_groups.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/picker_date.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/datatables_basic.js') ?>"></script>
<script src="<?php echo base_url('global_assets/js/demo_pages/datatables_api.js') ?>"></script>
<!-- /theme JS files -->